on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: notification
      uses: mras2303/giphy@v1.2
      with:
        botToken: 1036925454:AAE93Hmpt9N1e2TYNDjjsGNu-OcY_aOTUoI
        chatId: asdsad9
        jobStatus: ${{ job.status }}
